version: "3.8"
services:
    angular:
        build: 
            context: ./app
            dockerfile: Dockerfile
        ports: 
            - 4200:4200
            - 49153:49153
        volumes:
            - type: bind
              source: ./app/src
              target: /usr/app/src
    express:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports: 
            - 80:3000
        volumes:
            - type: bind
              source: ./app/dist/app
              target: /express/public
        depends_on: 
            - angular
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes: 
            - type: volume
              source: mongo_db
              target: /data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes: 
    mongo_db:
        external: true